title : API Evangelist

safe: true
lsi: false
pygments: true
auto: true

source: hacker-storytelling
destination: hacker-storytelling

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 10

production_url : http://hackerstorytelling.com

BASE_PATH : http://hackerstorytelling.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
